const calendarClassName = {
  datePicker: 'date-picker',
  datePickerOpened: 'date-picker_opened',
  datePickerWithError: 'date-picker_with-error',
  wrap: 'date-picker__wrap',
  control: 'date-picker__control',
  button: 'date-picker__button',
  buttonAccent: 'date-picker__button_accent',
  jsButtonClear: 'js-clear-button',
  jsButtonAccept: 'js-accept-button',
  sliderButton: 'date-picker__slider-btn',
  sliderButtonPrev: 'date-picker__slider-btn_prev',
  sliderButtonNext: 'date-picker__slider-btn_next',
  title: 'date-picker__title',
  calendar: 'date-picker__calendar',
  calendarHead: 'date-picker__calendar-head',
  calendarBody: 'date-picker__calendar-body',
  calendarDay: 'date-picker__day',
  calendarDayLower: 'date-picker__day_lower',
  calendarDayNotCurrent: 'date-picker__day_not-current',
  calendarDayCurrent: 'date-picker__day_current',
  calendarDaySelected: 'date-picker__day_selected',
  calendarDaySelectedStart: 'date-picker__day_selected-start',
  calendarDaySelectedEnd: 'date-picker__day_selected-end',
  calendarDaySelectedSpace: 'date-picker__day_selected-space',
  calendarDayWithError: 'date-picker__day_with-error',
}

export default calendarClassName
