import "./assets/scss/static/fonts.scss"
import "./assets/scss/header.scss"
import "./assets/scss/main.scss"
import "./assets/scss/footer.scss"
import "./assets/scss/colors.scss"
import "./assets/scss/cards.scss"
import "./assets/scss/form-elements.scss"

import "./functions/dropdown.js"
import "./functions/checkbox-buttons"